	<div class="showback"> 
		<h1><i class="fa fa-angle-right">Benvenuto nel nostro sito</i></h1>
		<hr>
		<h4><b>Informazioni generali</b></h4>
        	<p > Questo sito si occupa della gestione delle emergenze (terremoti, incendi, crolli di 
				porzioni di edifici ...) all'interno degli edifici di <b>Ingegneria</b>, <b>Economia</b> e <b>Medicina</b> dell'università Politecnica delle Marche, 
				fornendo indicazioni sui percorsi sicuri di fuga per gli occupanti degli stessi. Il nostro servizio è in grado di fornire le 
				planimetrie con i relativi percorsi di fuga personalizzati in base alle diverse tipologie di emergenze. 
        	    Il sistema acquisisce la posizione di ogni utente registrato all’interno dell’edificio in cui 
                si trova ed eventuali indicazioni di situazioni di pericolo segnalate dallo stesso. Su richiesta, fornisce una mappa 
                con l’indicazione della via di fuga più sicura per l’evacuazione, in relazione alla posizione del richiedente e alle 
                situazioni di pericolo in essere nell’edificio.</p>
         <h4><b>Piano evaquazione</b></h4>
             <p>Qualora sia necessario evacuare il Dipartimento:<br>
                L’allarme sarà dato mediante un’apposita sirena con suono prolungato seguito da avviso vocale
                Al primo avviso TUTTI sospenderanno la propria attività, abbandoneranno il proprio posto di lavoro
                e si recheranno ordinatamente all’esterno
                dell’edificio presso i LUOGHI DI RITROVO SICURO.
                Ciascuno deve aver già chiaro qual è la via più breve da percorrere per raggiungere il luogo di
                ritrovo sicuro dal proprio abituale luogo di lavoro (le planimetrie dei percorsi di fuga sono disponibili in questo sito).
                Il percorso deve essere effettuato ordinatamente, senza correre, senza provocare il panico.<br>
                Nell’abbandonare i luoghi di lavoro se possibile:
                <ul>
                   <li> La zona deve essere abbandonata senza indugi</li>
                   <li>NON usare gli ascensori o i montacarichi</li>
                   <li>Nell'abbandonare i luoghi di lavoro non devono essere portarti al seguito oggetti voluminosi, ingombranti o pesanti</li>
                   <li>Le attrezzature devono essere lasciate in sicurezza (chiudere eventuali rubinetti, chiudere bombole che erogano gas, spegnere eventuali attrezzature elettriche, ecc.)</li>
                   <li>Tutte le porte di accesso a scale protette a prova di fumo, dopo l’utilizzo, devono rimanere chiuse.</li>
                   <li>Le luci, se accese, vanno lasciate accese</li>
                   <li>La porta della stanza da cui si esce va chiusa, ma non a chiave</li>
                   <li>Defluire velocemente dalle uscite di sicurezza seguendo l’apposita segnaletica</li>
                   <li>Raggiungere i luoghi sicuri di raccolta all’esterno, rimanere uniti e verificare l’eventuale assenza di colleghi</li>
                </ul>
                Il ritorno ai luoghi di lavoro e la ripresa delle attività 
                è consentita solo dopo che la Squadra di primo intervento ha dichiarato
                la fine dell’emergenza ed il Coordinatore dell’Emergenza ha decretato la ripresa delle attività.
             </p>
           
            <a href="<?= $this->url(array(
                          'controller' => 'access',
                          'action'     => 'login', ), 
                          'default',true );?>">  
            <h4><b>Effettua il login o registrati per usufruire dei nostri servizi</b></h4></a>         
	</div>