<div class="col-md-2 col-sm-6 col-xs-6"></div>
<div class="col-md-2 col-sm-6 col-xs-6"></div>
<div class="col-md-3 col-sm-6 col-xs-6">
    
    <div class="GaugeMeter" data-percent="60" data-label="Percent" ></div>
    <div class="GaugeMeter" id="GaugeMeter_1" data-percent="10"></div>

    <script>
      $(document).ready(function(){
            $(".GaugeMeter").gaugeMeter();
      });
    </script>

    <?= $this->loginForm ?>
</div>