<div class="showback">
    <h2><i class="fa fa-angle-right">CHI SIAMO</i></h2>
    <hr>
    <div class="static">
    	<h4> <b>La nostra società</b></h4>    
    	     <p>Siamo un azienda specializzata nella sicurezza di grossi impianti industriali o scolastici.
    	        Ci occupiamo di studiare piani di evacuazione semplici ed efficienti, utilizzando
    	        anche supporti tecnologici come nel caso del sito in questione</p>
    	 
    	    <p>Il sito da noi creato è frutto di tante problematiche e difficoltà nella gestione delle emergenze che sono venute fuori durante gli anni.
    	       Il nostro gruppo si è fatto carico di trovare una soluzione semplice e facilmente implementabile anche in caso un utente si facesse prendere dal panico</p>
    <h4><b>Contattaci:</b></h4>
    <p>
       contatti e-mail:
       <ul>
           <li>Segreteria Univpm: <a  class="sub-menu" href="mailto:mingofilippo@gmail.com">segreteria@gmail.com</a>
           <li>Responsabile sicurezza ingegneria: <a  class="sub-menu" href="mailto:mingofilippo@gmail.com">sicurezzaing@gmail.com</a>
           <li>Responsabile sicurezza medicina: <a  class="sub-menu" href="mailto:mingofilippo@gmail.com">sicurezzamed@gmail.com</a>
           <li>Responsabile sicurezza economia: <a  class="sub-menu" href="mailto:mingofilippo@gmail.com">sicurezzaeco@gmail.com</a>
       </ul>
       contatti telefonici:
       <ul>
           <li>Segreteria Univpm: 071 7450553
           <li>Responsabile sicurezza ingegneria: 071 7680883
           <li>Responsabile sicurezza ingegneria: 071 9440714
           <li>Responsabile sicurezza ingegneria: 071 8045725
       </ul>
    </p>
    </div>
   
        
	