<nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
				<li class="text-center">
                    <img src="C:\xampp\htdocs\HackUnivpm\public\img\find_user.png" class="user-image img-responsive"/>
					</li>					
                    <li>
                        <a class="active-menu"  href="    <?= $this->url(array(
                                                    'controller' => 'public',
                                                    'action'     => 'index', ), 
                                                    'default',true );?>"
                                             ><i class="fa fa-dashboard fa-3x"></i> Home</a>
                    </li>
                     
                    <li>
                        <a  href="    <?= $this->url(array(
                                                    'controller' => 'public',
                                                    'action'     => 'info', ), 
                                                    'default',true );?>"
                                             ><i class="fa fa-qrcode fa-3x"></i> Informazioni</a>
                    </li>						   	
                </ul>
               
            </div>
            
</nav>  
<!-- /. NAV SIDE  -->
      