<nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
				<li class="text-center">
					<?php
	                  $base64 = base64_encode($this->authInfo('imgprofilo'));
	                  $image = '<img src="data:image/gif;base64,' . $base64 . '" class="user-image img-responsive" />';
	                ?>
					<?php echo $image ?>
					<h2 class="centered"><?php echo $this->authInfo('username') ?></h2>
					</li>					
                    <li>
                        <a class="active-menu"  href="    <?= $this->url(array(
                                                    'controller' => 'user',
                                                    'action'     => 'index', ), 
                                                    'default',true );?>"
                                             ><i class="fa fa-dashboard fa-3x"></i> Home</a>
                    </li>
                     <li>
                        <a  href="<?= $this->url(array(
                                                    'controller' => 'user',
                                                    'action'     => 'consumi', ), 
                                                    'default',true );?>"
                                             ><i class="fa fa-desktop fa-3x"></i> Consumi</a>
                    </li>
                    <li>
                    	<a href="#"><i class="fa fa-home fa-3x"></i> Gestione casa<span class="fa arrow"></span></a>
                    	<ul class="nav nav-second-level collapse" style="height: auto;">
                            <li>
                                <a href="<?= $this->url(array(
                                                    'controller' => 'user',
                                                    'action'     => 'gestioneprese', ), 
                                                    'default',true );?>"
                                             > Gestione prese</a>
                            </li>
                            <li>
                                <a href="<?= $this->url(array(
                                                    'controller' => 'user',
                                                    'action'     => 'assegnalp', ), 
                                                    'default',true );?>"
                                             > Assegna lista priorità</a>
                            </li>
                            <li>
                                <a href="<?= $this->url(array(
                                                    'controller' => 'user',
                                                    'action'     => 'pianificalp', ), 
                                                    'default',true );?>"
                                             > Pianifica lista priorità</a>
                            </li>
                            <li>
                                <a href="#"> Impostazioni lista priorità<span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level collapse">
                                    <li>
                                        <a href="<?= $this->url(array(
                                                    'controller' => 'user',
                                                    'action'     => 'crealp', ), 
                                                    'default',true );?>"
                                             > Crea</a>
                                    </li>
                                    <li>
                                        <a href="<?= $this->url(array(
                                                    'controller' => 'user',
                                                    'action'     => 'modificalp', ), 
                                                    'default',true );?>"
                                             > Modifica</a>
                                    </li>
                                    <li>
                                        <a href="<?= $this->url(array(
                                                    'controller' => 'user',
                                                    'action'     => 'eliminalp', ), 
                                                    'default',true );?>"
                                             > Elimina</a>
                                    </li>

                                </ul>
                               
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-user fa-3x"></i> Profilo<span class="fa arrow"></span></a>
                    	<ul class="nav nav-second-level collapse" style="height: auto;">
                            <li>
                                <a href="<?= $this->url(array(
                                                    'controller' => 'user',
                                                    'action'     => 'modificausername', ), 
                                                    'default',true );?>"
                                             > Modifica username</a>
                            </li>
                            <li>
                                <a href="<?= $this->url(array(
                                                    'controller' => 'user',
                                                    'action'     => 'modificapassword', ), 
                                                    'default',true );?>"
                                             > Modifica password</a>
                            </li>
                        </ul>
                    </li>						   	
                </ul>
               
            </div>
            
</nav> 

<a href="#"><i class="fa fa-sitemap fa-3x"></i> Multi-Level Dropdown<span class="fa arrow"></span></a>