<div class="sidebar-toggle-box">
                  <div class="fa fa-bars" data-placement="right" data-original-title="Toggle Navigation"></div>
</div>
            <!--logo start-->
            <a class="logo" href="<?= $this->url(array(
                          'controller' => 'user',
                          'action'     => 'index', ), 
                          'default',true );?>"> 
            <b>UNIVPM EMERGENCY</b></a>
            <!--logo end-->
            <div class="nav notify-row" id="top_menu"></div>
            <div class="top-menu">
                <ul class="nav pull-right top-menu">
                    <li><a class="login" href="    <?= $this->url(array(
                                                    'controller' => 'public',
                                                    'action'     => 'logout', ), 
                                                    'default',true );?>"
                                             >Logout</a></li>
                </ul>
            </div>