<!-- js placed at the end of the document so the pages load faster -->

    <script src="/Progetto_Teconologie_Web/public/js/jquery.js"></script>
    <script src="/Progetto_Teconologie_Web/public/js/jquery-1.8.3.min.js"></script>
    <script src="/Progetto_Teconologie_Web/public/js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="/Progetto_Teconologie_Web/public/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="/Progetto_Teconologie_Web/public/js/jquery.scrollTo.min.js"></script>
    <script src="/Progetto_Teconologie_Web/public/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="/Progetto_Teconologie_Web/public/js/jquery.sparkline.js"></script>


    <!--common script for all pages-->
    <script src="/Progetto_Teconologie_Web/public/js/common-scripts.js"></script>
    
    <script type="text/javascript" src="/Progetto_Teconologie_Web/public/js/gritter/js/jquery.gritter.js"></script>
    <script type="text/javascript" src="/Progetto_Teconologie_Web/public/js/gritter-conf.js"></script>

    <!--script for this page-->
    <script src="/Progetto_Teconologie_Web/public/js/sparkline-chart.js"></script> 