<!-- js placed at the end of the document so the pages load faster -->

    <script src="/HackUnivpm/public/js/jquery-1.10.2.js"></script>
    <script src="/HackUnivpm/public/js/bootstrap.min.js"></script>
    <script src="/HackUnivpm/public/js/custom.js"></script>
    <script src="/HackUnivpm/public/js/gauge.js"></script>
    <script src="/HackUnivpm/public/js/jquery.AshAlom.gaugeMeter-2.0.0.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js"></script>
    
    <script src="/HackUnivpm/public/js/jquery.metisMenu.js"></script>
    <script src="/HackUnivpm/public/js/dataTables/dataTables.bootstrap.js"></script>
    <script src="/HackUnivpm/public/js/dataTables/jquery.dataTables.js"></script>
    <script src="/HackUnivpm/public/js/morris/morris.js"></script>
    <script src="/HackUnivpm/public/js/morris/raphael-2.1.0.min.js"></script>