<!-- js placed at the end of the document so the pages load faster -->

    <script src="/js/jquery-1.10.2.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/custom.js"></script>
    <script src="/js/gauge.js"></script>
    <script src="/js/jquery.AshAlom.gaugeMeter-2.0.0.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js"></script>
    
    <script src="/js/jquery.metisMenu.js"></script>
    <script src="/js/dataTables/dataTables.bootstrap.js"></script>
    <script src="/js/dataTables/jquery.dataTables.js"></script>
    <script src="/js/morris/morris.js"></script>
    <script src="/js/morris/raphael-2.1.0.min.js"></script>
    <script>
    		
	function Login()
    {
    	var USERNAME = document.getElementById('username').value;
    	var pass = document.getElementById('password').value;
	        new Ajax.Request(
	        "<?=$this->url(array('controller' => 'access','action' => 'authenticate'))?>",
	            {
	                method:'POST',
	                parameters: {username : USERNAME,
	                			 password : pass},
	                onSuccess: function LoginRsp(loginRsp)
							   {
								   	var json = JSON.parse(loginRsp.responseText);
								   	if(json == true){
								   	    var ur="<?= $this->url(array('controller' => 'user','action'=>'index'))?>";
								   	    location.href = ur;
								   	}else{
								   	    alert("Errore durante il Login! Riprovare");								   	    
								   	}				   		   	
							   }
	        });
        
	}
    </script>