<script src="https://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js"></script>
<script>
	PericoloFunc();

    function FillPiani()
    {
    	//Metodo per prelevare l'elemento selezionato nel select
    	var e = document.getElementById('edificio');
		var edificio = e.options[e.selectedIndex].text;
		//Metodo per rimuovere tutti gli elementi e reinserire solo "-- Seleziona Piano --"
		$('#piano').find('option').remove().end().append('<option value="pian">-- Seleziona Piano --</option>').val('pian');
        new Ajax.Request(
        "<?=$this->url(array('controller' => 'user','action' => 'piano'))?>",
            {
                method:'get',
                parameters: {edif: edificio},
                onSuccess: function FillSelPiani(rsp)
						   {
						   		var piani = eval('(' + rsp.responseText + ')');
						   		var dim = piani.length;
								//Creazione dinamica del selettore
     							var select = document.getElementById('piano');
     							for (var i = 0; i<dim; i++){
								    var elemento = document.createElement('option');
								    elemento.innerHTML = piani[i].piano;
								    select.appendChild(elemento);
								}
						   }
        });
	}
	
	function FillMap()
    {
    	var e = document.getElementById('edificio');
		var edificio = e.options[e.selectedIndex].text;
    	//Metodo per prelevare l'elemento selezionato nel select
    	var p = document.getElementById('piano');
		var piano = p.options[p.selectedIndex].text;
		if(piano != '-- Seleziona Piano --'){
	        new Ajax.Request(
	        "<?=$this->url(array('controller' => 'user','action' => 'posizione'))?>",
	            {
	                method:'get',
	                parameters: {pia : piano,
	                			 edif : edificio},
	                onSuccess: function FillMapP(mappaRsp)
							   {
								   	var mappaEmap = eval('(' + mappaRsp.responseText + ')');
								   	var mappa = document.getElementById('mappaPosizione');
								   	mappa.src = mappaEmap.mappa;
								   	var map = document.getElementById('mapPosizione');
								   	map.innerHTML = mappaEmap.map;	
								   	mappa.setAttribute("usemap", "#mapPosizione");
								   	
								   	var area = map.getElementsByTagName("area"); 
									for (var i = 0; i < area.length; i++) { 
										var a = i+1;
										var url = "<?= $this->url(array('module'=>'default','controller' => 'user','action' => 'aula'))?>";
						
									    var status = area[i].setAttribute("href", url+"/au/"+a);	
									}						   		   	
							   }
	        });
        }
	}
	
	function MappaSegnalazione()
	{
    	//Metodo per prelevare l'elemento selezionato nel select
    	var a = document.getElementById('avvisi');
		var avviso = a.options[a.selectedIndex].text;
		if(avviso != '-- Seleziona Avviso --'){
	        new Ajax.Request(
	        "<?=$this->url(array('controller' => 'user','action' => 'mappasegnalazione'))?>",
	            {
	                method:'get',
	                parameters: {av : avviso},
	                onSuccess: function FillMapSe(mappaSeRsp)
							   {
							   		var mappaSeg = eval('(' + mappaSeRsp.responseText + ')');
							   		if(mappaSeg == 1){
							   			alert("Puoi inviare una sola segnalazione ogni 4 ore");
							   			document.getElementById('avvisi').selectedIndex = 0;
							   		}else{								   	
									   	var mappaSe = document.getElementById('mappaSegnalazione');
									   	mappaSe.src = mappaSeg.mappa;
									   	var mapSe = document.getElementById('mapSegnalazione');
									   	mapSe.innerHTML = mappaSeg.map;	
									   	mappaSe.setAttribute("usemap", "#mapSegnalazione");
									   	
									   	var area = mapSe.getElementsByTagName("area"); 
										for (var i = 0; i < area.length; i++) { 
											var a = i+1;
											var url = "<?= $this->url(array('module'=>'default','controller' => 'user','action' => 'aulasegnalazione'))?>";
							
										    var status = area[i].setAttribute("href", url+"/aus/"+a);
										    var status2 = area[i].setAttribute("onClick", "Notif()");	
										}
									}						   		   	
							   }
	        	});
        	}
		}
		
		function Notif(){
			alert("Segnalazione inviata");
		}
		
		var myVar = window.setInterval("PericoloFunc()", 60000);	
		var timer = null;	
				
		function PericoloFunc(){
			new Ajax.Request(
	        "<?=$this->url(array('controller' => 'user','action' => 'pericolo'))?>",
	            {
	                method:'POST',
	                onSuccess: function pericolo(pericoloRsp)
							   {
							   	    var a = 0;
							   		var pericolo = eval('(' + pericoloRsp.responseText + ')');
    								var pos = document.getElementById('apos');
    								pos.setAttribute("style","display:none");	
    								var inviaS = document.getElementById('inviaSegn');
    								inviaS.setAttribute("style","display:none");
    								
    								document.getElementById('pericoloText').innerHTML = "Pericolo: "+pericolo.tipoAvviso;
    								document.getElementById('mappaPericolo').src = pericolo.immEvac;
    								
    								window.clearTimeout(timer);
    								timer = window.setInterval("Sfondo()", 700);
							   }
	        	}); 
        	}
        	
        	
        	
        	function Sfondo()
			{
			    var sfondo = document.getElementById("ppos");
			    if (sfondo.getAttribute("style") == "background:white")
			    {
			    	sfondo.removeAttribute("style");
			    	document.getElementById("scrittaPer").setAttribute("style","color:white");			        
	  			  	sfondo.setAttribute("style","background:maroon");
	  			  	document.getElementById("pericoloText").setAttribute("style","color:white");
	  			  	document.getElementById("aulaPText").setAttribute("style","color:white");
	  			  	document.getElementById("scrittaA").setAttribute("style","color:white");
	  			  	document.getElementById("ancora").setAttribute("style","color:white");	
			    }
			    else
			    {
			    	sfondo.removeAttribute("style");
			    	document.getElementById("scrittaPer").setAttribute("style","color:#989898");			        
		    		sfondo.setAttribute("style","background:white");
		    		document.getElementById("pericoloText").setAttribute("style","color:#989898");
	  			  	document.getElementById("aulaPText").setAttribute("style","color:#989898");
	  			  	document.getElementById("scrittaA").setAttribute("style","color:#989898");
	  			  	document.getElementById("ancora").setAttribute("style","color:#989898");	
			    }
			}
			
		
</script>